version: '3'

services:

  medule-mongodb:
    container_name: medule-mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'medule'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  medule-api:
    container_name: medule-api
#    image: ghcr.io/choff3/medule-api:latest
    build:
      context: ./api
    restart: always
    environment:
      FHIR_SERVER_ENDPOINT: 'https://demo.kodjin.com/fhir'
      MONGO_USERNAME: 'medule'
      MONGO_PASSWORD: 'password'
      MONGO_ENDPOINT: 'medule-mongodb:27017'
    ports:
      - 5001:5001

  medule-frontend:
    container_name: medule-frontend
#    image: ghcr.io/choff3/medule-frontend:latest
    build:
      context: ./frontend
    restart: always
    environment:
      REACT_APP_API_ENDPOINT: 'http://medule-api:5001'
    ports:
      - 3000:3000

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  mongodb_data: